version: "3.9"

services:
  django:
    build: .
    container_name: django_chatbot
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
      DEBUG: "False"

      # Superuser Django auto
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@chatbot.info
      DJANGO_SUPERUSER_PASSWORD: admin

    volumes:
      - .:/app     
      - django_data:/app/db.sqlite3 

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  django_data:
  ollama_data:
